#!/bin/sh

set -e

now=$(date +%Y-%m-%d-%H-%M-%S)

cd -- "$(dirname -- "$0")"

find * -name Dockerfile | \
    while read -r dockerfile; do
        context=$(dirname -- "$dockerfile")
        name=$(basename -- "$context")
        repo=attemptthisonline/$name
        docker buildx build -t "$repo:latest" -t "$repo:$now" -- "$context"
        docker push -- "$repo:latest" 
        docker push -- "$repo:$now" 
    done

wait

echo "Finished; images tagged with $now"
