#syntax=docker/dockerfile-upstream:1.4.0-rc1
FROM attemptthisonline/base

RUN curl -fsSL https://raw.githubusercontent.com/Bubbler-4/rpaheui/66f153d454af2b2d21464b87fa67f953ab57f5ec/rpaheui -o /usr/local/bin/aheui && \
    chmod +x /usr/local/bin/aheui
