#syntax=docker/dockerfile-upstream:1.4.0-rc1
FROM attemptthisonline/python

ARG JELLY_REV=70c9fd93ab009c05dc396f8cc091f72b212fb188

RUN pip install https://github.com/DennisMitchell/jellylanguage/archive/$JELLY_REV.tar.gz
