#!/usr/bin/env bash
# to be run in the GCP Compute Engine VM
set -e
date

GCP_DOCKER_HUB_SECRET_NAME="$1"
DOCKER_HUB_USERNAME="$2"

echo setting up VM...
apt-get update
apt-get upgrade -y
apt-get install python-is-python3 git -y
mkfs.ext4 /dev/disk/by-id/google-local-nvme-ssd-0
mkdir -p /var/lib/docker
mount /dev/disk/by-id/google-local-nvme-ssd-0 /var/lib/docker
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y

echo logging in...
gcloud secrets versions access latest --secret="$GCP_DOCKER_HUB_SECRET_NAME" \
    | sudo docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

echo starting build...
cd "$(mktemp -d)"
git clone https://github.com/attempt-this-online/languages.git
cd languages
find . -name Dockerfile | ./knead
docker buildx bake --push
