FROM attemptthisonline/java

ARG KAMILALISP_VER=0.3.0.1

RUN curl -L https://github.com/kspalaiologos/kamilalisp/releases/download/v$KAMILALISP_VER/kamilalisp-$KAMILALISP_VER.jar -o /opt/kamilalisp.jar
