#syntax=docker/dockerfile-upstream:1.4.0-rc1
FROM attemptthisonline/java

ARG KAMILALISP_VER=v0.3.0.1

RUN curl -L https://github.com/kspalaiologos/kamilalisp/releases/download/$KAMILALISP_VER/kamilalisp-0.3.jar -o /opt/kamilalisp.jar
