#syntax=docker/dockerfile-upstream:1.4.0-rc1
FROM attemptthisonline/java

ARG KAMILALISP_VER=v0.2f

RUN curl -L https://github.com/kspalaiologos/kamilalisp/releases/download/$KAMILALISP_VER/kamilalisp-0.2.jar -o /opt/kamilalisp.jar
