FROM registry.gitlab.pxeger.com/attempt-this-online/languages/python

RUN curl -L https://github.com/jfioasd/minigolf/archive/refs/tags/tag0.6.tar.gz | \
    tar -xz && \
    mv minigolf-tag0.6 /opt/minigolf
