FROM attemptthisonline/whython

ARG EXCEPTIONALLY_REV=cee69c6fa739d5f6606172f312fabb20ff73ad3d

RUN curl -L https://github.com/dloscutoff/Esolangs/raw/$EXCEPTIONALLY_REV/Exceptionally/exceptionally.why -o /opt/exceptionally.why
