#syntax=docker/dockerfile-upstream:1.4.0-rc1
FROM attemptthisonline/python

ARG FLAX_REV=3adeb6b1f40f46413d72c72d47e61ce8ea581eb6

RUN pip install https://github.com/PyGamer0/flax/archive/$FLAX_REV.tar.gz
