#syntax=docker/dockerfile-upstream:1.4.0-rc1
FROM attemptthisonline/python

ARG FLAX_REV=5f9bab8361882f945621c9114a60fad0ef6177d4

RUN pip install https://github.com/PyGamer0/flax/archive/$FLAX_REV.tar.gz
