#syntax=docker/dockerfile-upstream:1.4.0-rc1
FROM attemptthisonline/python

ARG FLAX_REV=22c2c4082c3f34a5b40b50d49909b1c9d0c957b3

RUN pip install https://github.com/PyGamer0/flax/archive/$FLAX_REV.tar.gz
