#syntax=docker/dockerfile-upstream:1.4.0-rc1
# This is for languages which depend on python but where it's simplest to use pacman's version instead of custom-built

FROM attemptthisonline/base

RUN pacman -Syu --noconfirm python
