# This is for languages which depend on python but where it's simplest to use pacman's version instead of custom-built

FROM registry.gitlab.pxeger.com/attempt-this-online/languages/base

RUN pacman -Syu --noconfirm python
